name: atelierul_digital_tema5
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  loading_animation_widget: ^1.2.0+3
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  very_good_analysis: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:


  uses-material-design: true
